In [1]:
import tracers as tr
import numpy as np
import plotly.graph_objects as go

In [2]:
mypygraph = tr.PyGraph()
print(mypygraph.yendepth)

mypygraph.load_graph("/home/toon/Documents/PHD/coding/osrm-docker/data-volume/monaco/monaco-latest.osm.pbf")

2

Reading in the test matched file

In [3]:
infile = r"/home/toon/Documents/PHD/coding/pyrust-docker/tracers/tests/testout/_0.csv"

#even lines are the matched points
#odd lines are the original input

matches = []
ogpoints = []

with open(infile, "r") as f:
    for matchline in f:
        matchline = matchline.rstrip()  # remove newline character
        if matchline:
            # process matchline, it has format int,float,float,int|...
            strtupls = matchline.split("|")
            matches.append([(int(split[0]),float(split[1]),float(split[2]),int(split[3]))for split in [x.split(",") for x in strtupls]])

        # origline
        origline = f.readline()
        #strip
        origline = origline.rstrip()
        if origline:
            # process origline, it has format float,float,int|...
            split = origline.split(",")
            ogpoints.append((float(split[0]),float(split[1]),int(split[2])))

In [6]:
match_nodeids = [[mypygraph.osm_to_nodeid(
    a) for a, b, c, d in match] for match in matches]
print(match_nodeids)
match_nodeids = [[a for a in b if a != None] for b in match_nodeids]
match_nodeids

og_lonlats = [(a, b) for a, b, _c in ogpoints]

[[3284, 3283, 3282, 3933, 3934, 3935, 3676, 4137, 4136, 3176, 3175, 3174, 3173, 1736, 1735, 3500, 3499, 2275, 3098], [3098, 3091, 3092, 3093, 3094, 3095, 3096, 2381, 3097, 2406, 2407, 2408, 2409, 2410, 2411, 2412, None, 1803, 4266, 4267, 1037, 1038, 1039, 1040, 269, 3775, 3776, 188, 3834, 3835, 3836, 3837], [3837, 187, 3742, 3743, 3744, 3745, 3746, 2471, None, 2472, 2474, 996], [996, 997, 998, 999, None, None, 976, None], [None, 841, 842, 113, 843, 844], [844, 845, 1121, None, 982, 983, 984, 985, 986, 987, 988, 989, 990, 991, 992, 993, 994, 995, 4256, 4257, 4258, 4259, 4260, 4261, 4262, 4263, 4264, 4265, 4435, 4436, 1422, 1421, 1420, 1419, 4348, 4347, 4346, 4345, 3571, 4351, 4350, 4349, 3596, 3808, 3187, 3578, 3579, 3580, 4037, 4038, 4036, 1155, 2969, 2970, 4468, 4030, 4031, 4032, 4148, 4149, 4150, 1850, 4144, 4145, 4146, 4147, 2635, 2636, 2637, 2638, 2639, 2640, 2641, 2642, 2145, 2146, 2147, 2148, 2149, 2150, 2151, 82, 2152, 2153, 2154, 2155, 2533, 3572, 3573, 3574, 3575, 3576, 3577, 124, 2429, 2430, 2431, 2432, 2433, 255, 2035, 2036, 2037, 2580, 2581, 2582, 2583, 2584, 2585, 2586, 877, 878, 879, 880, 49, 50, 51, 52, 53, 54, 55, 56, 57, 4395], [4395, 4396, 4397, 4398, 4399, 4400, 4401, 4402, 4403, 4404, 4405, 4406, 4407, 4408, 4409, 4410, 4411, 4412, 2297, 2298, 2299, 2043, 2300, 2301, 2302, 2303, 2304, 2305, 2306, 2307, 2308, 2309, 2310, 2311, 2312, 1911, 2313, 2314, 2315, 2316, 2317, 2318, 2319, 2320, 2321, 2322], [2322, 2323, 2324, 2325, 2326, 158, 2038, 2039, 2177, 2021, 2332, 2333, 2334, 2335, 155, 1605, 1606, 1607, 1608, 1609, 1610, 1611, 1612, 1613, 1187, 3353, 3354, 3355, 3356, 3357, 3358, 3359, 3360, 2435, 2436, 2437], [2437, 2438, 2439, 2440, 2441, 2442, 2443, 200, 795, 794, 793, 792, 791, 790, 789, 788, 787, 786, 785, 784, 783, 782, 781, 780, 779, 778, 777, 776, 775, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], [16, 17, 1641, 1642, 1643, 1644, 1645, 1646, 1647, 1648, 245, 2672, 2671, 2670, 2669, 2668, 2667, 2666, 2665, 2664, 2663, 2662, 2661, 2660, 2792, 2793, 2794, 2795, 2796, 2797, 2798, 2568, 2569, 2570, 2571, 2572, 2573, 2574, 2090, 2182], [2182, 1649, 1650, 1651, 1652, 1653, 1654, 1655, 1656, None]]

In [14]:
res = mypygraph.extract_features_labeled_pert(match_nodeids, og_lonlats)
# convert to pd df
import pandas as pd
df = pd.DataFrame(res, columns=["step_d","step_bear","roadtype","emit_a_d","emit_a_bear","emit_b_d","emit_b_bear","y"])
df

,step_d,step_bear,roadtype,emit_a_d,emit_a_bear,emit_b_d,emit_b_bear,y
0,3.216260,122.140601,4.0,55.407827,-130.456219,148.861720,-16.451614,1.0
1,3.221507,-76.029397,4.0,49.266566,-132.257103,150.086327,-14.060370,0.0
2,0.000000,NaN,13.0,52.466678,-131.839357,148.942262,-15.214422,0.0
3,3.222179,140.569434,4.0,57.856318,-128.336441,149.868153,-17.625799,1.0
4,3.216260,-57.859376,4.0,52.466678,-131.839357,148.942262,-15.214422,0.0
...,...,...,...,...,...,...,...,...
909,0.000000,NaN,13.0,69.085036,-136.838603,83.139266,-34.640761,0.0
910,4.316968,-69.510984,6.0,80.415091,-138.842698,78.701617,-42.257911,1.0
911,0.000000,NaN,13.0,76.668125,-137.278177,81.289801,-39.782714,0.0
912,4.481972,-92.130998,6.0,83.271727,-141.261067,74.929258,-44.063769,1.0
913,0.000000,NaN,13.0,80.415091,-138.842698,78.701617,-42.257911,0.0